[package]
name = "bc_utils_state_gw"
version = "0.2.0"
edition = "2024"

[dependencies]
bc_utils_lg = {path = "../bc_utils_lg"}
bc_utils = {path = "../bc_utils"}
bc_utils_state = {path = "../bc_utils_state"}

[dev-dependencies]
pretty_assertions = "1"
criterion = {version = "0.8", features = ["html_reports"]}
bc_packs = {path = "../bc_packs"}
