[package]
name = "bc_utils_state_gw"
version = "0.6.0"
edition = "2024"

[dependencies]
bc_utils_lg = {path = "../bc_utils_lg", features = ["test_state"]}
bc_gw_utils = {path = "../bc_gw_utils"}
bc_utils_state = {path = "../bc_utils_state"}

[dev-dependencies]
bc_test_kit = {path = "../bc_test_kit"}
criterion = {version = "0.8", features = ["html_reports"]}
bc_packs = {path = "../bc_packs"}

[features]
test_state = []